/** @type {import('tailwindcss').Config} */
// Obsidian Velocity design tokens — see template_reference/obsidian_velocity/DESIGN.md
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#141313",
        "surface-dim": "#141313",
        "surface-bright": "#3a3939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1c",
        "surface-container": "#201f20",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353435",
        "surface-variant": "#353435",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#c7c6cb",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        outline: "#919095",
        "outline-variant": "#46464b",
        "surface-tint": "#c7c6cb",
        primary: "#c7c6cb",
        "on-primary": "#2f3035",
        "primary-container": "#0b0c10",
        "on-primary-container": "#7a7a7f",
        "inverse-primary": "#5e5e63",
        "primary-fixed": "#e3e2e8",
        "primary-fixed-dim": "#c7c6cb",
        "on-primary-fixed": "#1a1b20",
        "on-primary-fixed-variant": "#46464b",
        secondary: "#bec7d6",
        "on-secondary": "#28313c",
        "secondary-container": "#3e4753",
        "on-secondary-container": "#adb6c4",
        "secondary-fixed": "#dae3f2",
        "secondary-fixed-dim": "#bec7d6",
        "on-secondary-fixed": "#131c27",
        "on-secondary-fixed-variant": "#3e4753",
        tertiary: "#cfc5b9",
        "on-tertiary": "#353028",
        "tertiary-container": "#100c06",
        "on-tertiary-container": "#81796f",
        "tertiary-fixed": "#ebe1d5",
        "tertiary-fixed-dim": "#cfc5b9",
        "on-tertiary-fixed": "#201b14",
        "on-tertiary-fixed-variant": "#4c463d",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#141313",
        "on-background": "#e5e2e1",
      },
      fontFamily: {
        display: ["'Space Grotesk'", "system-ui", "sans-serif"],
        sans: ["'Space Grotesk'", "system-ui", "sans-serif"],
        mono: ["'JetBrains Mono'", "ui-monospace", "monospace"],
      },
      spacing: {
        unit: "4px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "container-max": "1440px",
      },
    },
    borderRadius: {
      none: "0",
      sm: "0.125rem",
      DEFAULT: "0.25rem",
      md: "0.375rem",
      lg: "0.5rem",
      xl: "0.75rem",
      full: "9999px",
    },
  },
  plugins: [],
}
