export const vehicleBrands = [
  "Tata",
  "Honda",
  "Kia",
  "Mahindra",
  "Maruti Suzuki",
  "MG",
  "Hyundai",
  "Toyota",
  "Skoda",
  "Volkswagen",
] as const;

// Current India line-ups (mid-2026).
const vehicleModelsByBrand: Partial<Record<(typeof vehicleBrands)[number], readonly string[]>> = {
  Tata: [
    "Tiago",
    "Tigor",
    "Altroz",
    "Punch",
    "Nexon",
    "Curvv",
    "Harrier",
    "Safari",
    "Nexon EV",
    "Punch EV",
    "Harrier EV",
  ],
  Honda: ["Amaze", "City", "Elevate"],
  Kia: ["Sonet", "Seltos", "Syros", "Carens", "Carens Clavis", "Carnival", "EV6"],
  Mahindra: [
    "Bolero",
    "Thar",
    "Thar Roxx",
    "Scorpio Classic",
    "Scorpio-N",
    "XUV 3XO",
    "XUV700",
    "BE 6",
    "XEV 9e",
  ],
  "Maruti Suzuki": [
    "Alto K10",
    "S-Presso",
    "Celerio",
    "Wagon R",
    "Swift",
    "Baleno",
    "Dzire",
    "Fronx",
    "Brezza",
    "Grand Vitara",
    "Victoris",
    "Ertiga",
    "XL6",
    "Jimny",
    "Invicto",
    "e Vitara",
  ],
  MG: ["Hector", "Hector Plus", "Astor", "Gloster", "Comet EV", "ZS EV", "Windsor EV", "M9 EV"],
  Hyundai: [
    "Grand i10 Nios",
    "Aura",
    "i20",
    "Exter",
    "Venue",
    "Verna",
    "Creta",
    "Creta Electric",
    "Alcazar",
    "Tucson",
    "Ioniq 5",
  ],
  Toyota: [
    "Glanza",
    "Urban Cruiser Taisor",
    "Rumion",
    "Urban Cruiser Hyryder",
    "Innova Crysta",
    "Innova Hycross",
    "Fortuner",
    "Hilux",
    "Camry",
    "Vellfire",
  ],
  Skoda: ["Kylaq", "Kushaq", "Slavia", "Kodiaq", "Superb"],
  Volkswagen: ["Virtus", "Taigun", "Tiguan R-Line", "Golf GTI"],
};

export function modelsForBrand(brand: string): readonly string[] {
  return vehicleModelsByBrand[brand as keyof typeof vehicleModelsByBrand] ?? [];
}
